<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MARJAN - Latest News</title>
   <link rel="stylesheet" href="./news.css">
   <link rel="shortcut icon" href="https://assets-global.website-files.com/64a2ab71942e1d57feb6fe39/6528221f95333ff155d01ad2_fav.gif" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/remixicon@4.2.0/fonts/remixicon.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Sora:wght@100..800&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/locomotive-scroll@3.5.4/dist/locomotive-scroll.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/gsap.min.js"
        integrity="sha512-7eHRwcbYkK4d9g/6tD/mhkf++eoTHwpNM9woBxtPUBWm67zeAfFC+HrdoE2GanKeocly/VxeLvIqwvCdk7qScg=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/ScrollTrigger.min.js"
        integrity="sha512-onMTRKJBKz8M1TnqqDuGBlowlH0ohFzMXYRNebz+yOcc5TQr/zAKsthzhuv0hiyUKEiQEQXEynnXCvNTOk50dg=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</head>
</head>
<body>
    <!-- Navigation -->
    <nav>
        <a href="../first-page/home.php"><h1 id="nav-bottom"><span>M</span>ARJAN</h1></a>
        <div class="nav-part2">
            <h4><a href="../about-us/about-us.php">About</a></h4>
            <h4><a href="../first-page/home.php">Home</a></h4>
            <h4><a href="./news.php">News</a></h4>
        </div>
        <button class="cta-button">
            <a href="../partnership/project/index.php">BECOME A PARTNER</a>
            <div class="icon">
                <span>
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 36 36" fill="none">
                        <path d="M1.05403 31.6175C0.271626 32.3972 0.271626 33.6614 1.05403 34.441C1.83644 35.2207 3.10497 35.2207 3.88737 34.441L1.05403 31.6175ZM35.5599 2.05152C35.5599 0.948871 34.6629 0.0549994 33.5564 0.0549994L15.5251 0.0549994C14.4187 0.0549994 13.5217 0.948871 13.5217 2.05152C13.5217 3.15416 14.4187 4.04804 15.5251 4.04804H31.5529V20.0202C31.5529 21.1228 32.4499 22.0167 33.5564 22.0167C34.6629 22.0167 35.5599 21.1228 35.5599 20.0202L35.5599 2.05152ZM3.88737 34.441L34.9731 3.46327L32.1397 0.639766L1.05403 31.6175L3.88737 34.441Z" fill="#F5A091" />
                    </svg>
                </span>
            </div>
        </button>
    </nav>

    <div id="main"> 
        <!-- Hero Section -->
        <div id="page1">
            <img src="https://cdn.snrtnews.com/sites/default/files/2023/02/21/2-marjane-holding-1676996028.jpg" alt="News Background">
            <h1>Latest News</h1>
        </div>

        <!-- News Content Section -->
        <div id="page2">
            <div id="items">
                <h2 class="section-title">Featured Stories</h2>
                
                <!-- Featured Article -->
                <div class="items1" id="featured-article">
                    <!-- Content will be generated by JavaScript -->
                </div>

                <h2 class="section-title">Latest Updates</h2>
                
                <!-- Dynamic News Grids (Generated by Loops) -->
                <div id="news-container">
                    <!-- News grids will be generated by JavaScript loops -->
                </div>

                <!-- Loading indicator -->
                <div class="loading" id="loading">Loading more articles</div>

                <!-- Final Section with Image -->
                <div class="final-section">
                    <div class="section-image">
                        <div class="section-overlay">
                            <div class="section-content">
                                <h2>Stay Connected with MARJAN</h2>
                                <p>Join our community of innovators and stay updated with the latest developments in technology, business, and research. Together, we're shaping the future of digital innovation.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
           <!-- Enhanced Footer Section -->
           <div class="footer-section">
            <div class="footer-container">
                <div class="footer-content">
                    <div class="footer-about">
                        <h3>ABOUT MARJAN</h3>
                        <p>MARJAN is dedicated to connecting investors with high-potential startups. Our platform provides opportunities to invest in innovative companies, offering the potential for significant returns while supporting visionary entrepreneurs.</p>
                        
                        <div class="social-links">
                            <a href="#" class="social-link">
                                <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor">
                                    <path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"/>
                                </svg>
                            </a>
                            <a href="#" class="social-link">
                                <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor">
                                    <path d="M22.46 6c-.77.35-1.6.58-2.46.69.88-.53 1.56-1.37 1.88-2.38-.83.5-1.75.85-2.72 1.05C18.37 4.5 17.26 4 16 4c-2.35 0-4.27 1.92-4.27 4.29 0 .34.04.67.11.98C8.28 9.09 5.11 7.38 3 4.79c-.37.63-.58 1.37-.58 2.15 0 1.49.75 2.81 1.91 3.56-.71 0-1.37-.2-1.95-.5v.03c0 2.08 1.48 3.82 3.44 4.21a4.22 4.22 0 0 1-1.93.07 4.28 4.28 0 0 0 4 2.98 8.521 8.521 0 0 1-5.33 1.84c-.34 0-.68-.02-1.02-.06C3.44 20.29 5.7 21 8.12 21 16 21 20.33 14.46 20.33 8.79c0-.19 0-.37-.01-.56.84-.6 1.56-1.36 2.14-2.23z"/>
                                </svg>
                            </a>
                            <a href="#" class="social-link">
                                <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor">
                                    <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/>
                                </svg>
                            </a>
                            <a href="#" class="social-link">
                                <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor">
                                    <path d="M12.017 0C5.396 0 .029 5.367.029 11.987c0 5.079 3.158 9.417 7.618 11.174-.105-.949-.199-2.403.041-3.439.219-.937 1.406-5.957 1.406-5.957s-.359-.72-.359-1.781c0-1.663.967-2.911 2.168-2.911 1.024 0 1.518.769 1.518 1.688 0 1.029-.653 2.567-.992 3.992-.285 1.193.6 2.165 1.775 2.165 2.128 0 3.768-2.245 3.768-5.487 0-2.861-2.063-4.869-5.008-4.869-3.41 0-5.409 2.562-5.409 5.199 0 1.033.394 2.143.889 2.741.099.12.112.225.085.345-.09.375-.293 1.199-.334 1.363-.053.225-.172.271-.402.165-1.495-.69-2.433-2.878-2.433-4.646 0-3.776 2.748-7.252 7.92-7.252 4.158 0 7.392 2.967 7.392 6.923 0 4.135-2.607 7.462-6.233 7.462-1.214 0-2.357-.629-2.75-1.378l-.748 2.853c-.271 1.043-1.002 2.35-1.492 3.146C9.57 23.812 10.763 24.009 12.017 24.009c6.624 0 11.99-5.367 11.99-11.988C24.007 5.367 18.641.001.001 12.017z"/>
                                </svg>
                            </a>
                        </div>
                        
                        <div class="footer-buttons">
                            <a href="#" class="footer-btn">JOIN US NOW</a>
                            <a href="#" class="footer-btn secondary">EXPLORE CAMPAIGN</a>
                        </div>
                    </div>
                    
                    <div class="footer-column">
                        <h4>LEARN MORE</h4>
                        <ul>
                            <li><a href="#">HOME</a></li>
                            <li><a href="#">ABOUT</a></li>
                            <li><a href="#">BLOG</a></li>
                            <li><a href="#">CAREERS</a></li>
                            <li><a href="#">RESOURCES</a></li>
                        </ul>
                    </div>
                    
                    <div class="footer-column">
                        <h4>DISCOVER CAMPAIGN</h4>
                        <ul>
                            <li><a href="#">FEATURED CAMPAIGNS</a></li>
                            <li><a href="#">RECENTLY LAUNCHED</a></li>
                            <li><a href="#">TOP PERFORMING</a></li>
                            <li><a href="#">SUCCESS STORIES</a></li>
                            <li><a href="#">INVESTMENT GUIDE</a></li>
                        </ul>
                    </div>
                    
                    <div class="footer-column">
                        <h4>SUPPORT</h4>
                        <ul>
                            <li><a href="#">TERMS OF SERVICE</a></li>
                            <li><a href="#">PRIVACY POLICY</a></li>
                            <li><a href="#">CONTACT US</a></li>
                            <li><a href="#">HELP CENTER</a></li>
                            <li><a href="#">INVESTOR SUPPORT</a></li>
                        </ul>
                    </div>
                </div>
                
                <div class="footer-bottom">
                    <p>© 2024 MARJAN. All rights reserved.</p>
                    <div class="footer-legal">
                        <a href="#">Privacy Policy</a>
                        <a href="#">Terms of Service</a>
                        <a href="#">Cookie Policy</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    

    <script>
        /**
         * LOOP FUNCTIONALITY DEMONSTRATION
         * This script demonstrates various JavaScript loop types:
         * 1. FOR LOOP - Generate news articles
         * 2. FOREACH LOOP - Handle animations and event listeners
         * 3. WHILE LOOP - Simulate loading process
         * 4. FOR...OF LOOP - Iterate through arrays
         * 5. FOR...IN LOOP - Iterate through objects
         */

        // Sample data arrays for loop demonstrations
        const newsData = [
    {
        category: "Promotion",
        title: "Mega Sale on Fresh Produce – Up to 50% Off This Week!",
        date: "August 13, 2025",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQ1UE8194ignFq_0yZnuvEqBftX3Vb1TEK8g&s"
    },
    {
        category: "New Update",
        title: "Marjane lance sa marque de produits alimentaires frais « Filière Exclusive M »",
        date: "August 10, 2025",
        image: "https://www.foodmagazine.ma/wp-content/uploads/2021/11/Visuel-Filie%CC%80re-Exclusive-M-VF.jpg"
    },
    {
        category: "Promotion",
        title: "Back-to-School Deals on Stationery and Supplies",
        date: "August 8, 2025",
        image: "https://www.marjanemall.ma/media/wysiwyg/tendance-du-moment-back-to-school-Sac-_-dos-et-trousse_1_.webp"
    },
    {
        category: "Event",
        title: "Cooking Workshop: Learn to Make Moroccan Couscous at Marjane",
        date: "August 5, 2025",
        image: "https://chama-morocco.com/wp-content/uploads/2024/09/6e.jpg"
    },
    {
        category: "Launch",
        title: "Exclusive Launch: Marjane Organic Product Line",
        date: "August 3, 2025",
        image: "https://en.7news.ma/wp-content/uploads/2024/10/Marjane-City.jpg"
    },
    {
        category: "Community",
        title: "Marjane Supports Local Farmers with Fresh Market Days",
        date: "August 1, 2025",
        image: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxMTEhUTExMWFhUXGRoYGRgYGCAZGxgbGBkZGBgYGCAaHSggGholHhcfITEhJSkrLi4uGCAzODMsNygtLisBCgoKDg0OGxAQGy0mICUtLy0tKy8tLy0tMC0tNTUtLS0tLy0uLS0wLS0tMC0rLS0tLSstLS0tLS0tLS0tLS0tLf/AABEIAMIBBAMBIgACEQEDEQH/xAAbAAACAgMBAAAAAAAAAAAAAAAEBQMGAAECB//EAEQQAAIBAgQDBgQDBgUDAgcBAAECEQMhAAQSMQVBUQYTImFxgTKRobFCUsEUI2Jy0fAVM6Ky4QeCkkPxJGN0k8LD0hb/xAAaAQACAwEBAAAAAAAAAAAAAAABAgADBAUG/8QAMREAAgIBAwIDBgYCAwAAAAAAAAECEQMSITEEQRMiUQVhcYGhsSMykcHR8BThQlJT/9oADAMBAAIRAxEAPwBvSFChEAu0fGbj0Ec/7nCvj/Haug6Dp89z7ch9/PFf4czd6BJi4Im2xww4un7s+/2xSWFaq1WYlmYsTuSZJ+eLj/03rU0asXYAwmlebAai0DnFsU0DHSjBCXHg3ZevUzIJSQupiQZEkW+/PAvHeEVcvX/eIV1TE7HnY88Fdh+0tTK6ralZjIJvcLJn2+mH/antcuZo92KUXBk8oPLz5e5wlhKcpxIpxpBiZac4IDQY44p5ip3hBQaIkMG8U23BEAb8+WIK3EKSb1F9vF/tkD3xp8yTemA9usfMb8/LBoljLO150Gn4YEMG/EbXBkxztGIRmx+Lwno3v032xXc3nKpsWK+Q8P13+Zx1wwSB74KQGxlm+M6TCoSf4vD9Bcj3GFn+J1ncAvAJ2Xwj0MXPuThnVppEEgfb5f0jC7/D6hqAohIHPYf6oP3wUKxpQWIi2Js1RWoIcAnrsfnjlMrU5lV/1H9I+uJf8NWJZmb1MD5LH1xLCVipRCVR4gRPuP64eU6jn4KbnzI0j/VGGmWyqqPCoX0EYn0YlgFP7NWbdlS/KWPP0H3xh4Uh+Ms/kTA+Sx9cNWpmJgx9L9cZTolvhBPoCftiWQCy+TRLIir6ADBATDGhwWs34I/mMf8AOCG4Uif5tdF8pE/U/pgWETCneAJJtGOOPZCtRp6ilhcwb4cHP5KiQ2tmZbg8gRebwMG5vj4OXOYpKakMqhSTJLMqwI/m5TtgNsKKnwajWqrIpOB5qR94w6pdnHbxMqA9TcjA/FuL5ykJqhqQY2lQpgmwmJ98JK/FHf4nZvUk/fBIWo8PoJ/mVx6KQPtJxG2dydP4UL+o/wD6P6YolfOtTktqaBsIAj839enpjnI8SNQSEC35mdvliVYLou9TtPFqdJR63+0DCz/H8ywOpwt/wALI69frhP3h5tjRqqN2+ZwdJNQJWzIeoatWsQtxpdyQGBMwD5Rt1wZSzFMiVk+39cIeJp3hhbjVNhNwTq26iPlhjSqsB4aZ97ffEQD0Ls3w6lUoKzU1JJNyL74zFd4X2ozFGmKa0aRAm7MZv6WxmEaY5MmWyzMKmXaoVBI8ahbxe0k88b4kvg/vocRcCoaaX8x1ekgCPpgrOL4Dgit7lPAx0BjQGN4IRpwekWDxFrm4FtpgmT7Y5r8URRYM/wDKIHuTcfLCz9jNSSGAIHzmZ/vzxJwvh1QOdSeHz29pxKI2RVu0NQQURF9ZbpzkD6DBOXH7QAzFwf5iwHoG29sF5vgyPv4fS/8Au/TBWR4YlNQok+p/pGDQtiDO8NZNvEPLDfhVFgFOhpg7iOnXDSmgBsIsP1wRNx6H7riAAa+TNQQ0D6nHOU4SiC0n1P8ASMMTUQD4l+eITmByv74Fho6SiF2AHoMdouAc1ntO5Ueu+IaGc1FdTkISJItA5ke2BY1DZoG9scVc0gBvNuWFObzDDxMIVp0NFiAfLniFKtrkE+VvvfEJQxHGEFiCrdGt8jsfbDzKVcoSimozu0DSogAnlcfrin1K3Ix98X/svkw+SotTp7Pcqu+lzJMC+2ITYW5ntFQpM9OnRBZGIbXtIsCN5G/TC/M9sK5suhP5V/Vpwj41IzVZgpZXckEDzO43Hv0wKQ/5Y9SMQAXxHtFViaj1G9CY+8YBy+fNQEgEX5n16Y5zgA0g1V8SyfCYBkjT52gz544o0QqkKzbj4QB19cFUTcIq0NXxRbpy5b4smWzKjhoRXDVRWRiOYArK0nkPCs4qZpjmrH+Zv0JxHlmAgIqqPIefkMGyHov/AFL4hRqpTFKrTqMAJCMHI9dJMYo4qNyQ+pIH6zjeZy1RKhp1H0m0kXAkAzKzIvyBxDmQqvoVjVsCWEgDykgTgWFm8zQZxdkU+Xij12t5YhpZZEAUVD6AR95xJI/hHqZ++OjUMWPyGCA7C07fu2Y+ZYT9Y+mNhfy00HsPuMLkzBU6WZ2YyRAAEYLU/wAPzOAQx8y40+IQZBi43mT8zjtMwDP7ySDBAB39wfviEHwiY2/TAK1iHjWAp2AFyeZMCf8A3xCDK3RvnjMDd55tjMQlln7OUKwV+9cOSwIIOwjbYRtywxzbKFMsB7+eKvwXjJrllK6dIBsd5nz/ALnDGotjjLl6jRKkjrdH7LWbGskpfISAjkR88dacLswvib1P3xyrEbEj3xF1Pqhpey/+svoWHg06z0i/6ffDV6q9RimDPMkkmRHMT5+WOhxR4DAiPZfvfl1xohPUrRzc+B4p6ZMtxqjlPywNX4mF3Kj1N8V1849Rfwb7EFj+owx4Zlq1ZT3jOoBFwCLExO3Lc4Yp2CxmjUGoOQNp+H7jANXNw4mqhGxMyR7AYDy/DnVjr0R0d7g78hiQ5TSZA3kHSOUdXaDf+ziUSwzOZsKLLVPmoH3M4iyFZ2LxEA/iJ6bTsPljRr2uz+7QB/8AbH642rqSYCmN/Dq9LscQlklXNxY3/l8X0W/0w27I9yMyjV/3aLJBNlLcgw5c9xhJ+1GdMNHXUoHyEnA+ZzAmAU1dCGb7nEIWbj2V76qzUEinqjSvwizEkDZRblaTiTi3ZmplURq6sdYsF09BOrmMIadVkAI1AiPgAXE/GONVcwA9epMWGsxH6csK07GTVEPcqT8PszA/Y/pggZmqiFVJROiiQetpwHwuoNRIFo3mQb8oxZadSgMsfF+/ZgASSugdZ2IPMX+2GFK1V4kmo6u9b3Cj7HGft1PlSUfzEtz+WN5/glajlhmGVdDtCAuPHz1KBJK+Ywv4ejVWFNKbFzyUEjz+XlgIIb/iR5aR6KBiJaoAO+4522blsML8whDwGFjEWv6EicR/tTKG1qEuI3ad+kf2cGgDF3BFxIxBSd4AQgCb2E79cLBUF2Q6SeZA/XGftbAxBIk3kgD2Aw1Asd/tKyRqZiN949vLHFfSwgi3rhXUqEgWPtb7nHNNnk7R7T9jiUCxjSqd3AAUKB8RMYIGann8hhYNZ6fOf0GOBQbcvv5GPa9sSgjKtUB2JHnzHzxymZHOZ8zv52OF2lJANUCf5R+hOOAaVyHJPkSefl54lEGf7SPL74Dq5gBpkb9L339NpwEKwgShv1n9cEU6V70wOnh9PLAogV+0jqfmMZhQBjMKEd9iUbv2B2NM/Rl/ri6tSsfTFe7MZHTVpuQQKiOUkg6gCQxttBTni3d1jn9V+c9T7J36f5soeeSKjep+t8Dxg7ii/vW9vsMCRipM0yjuRlJmxIAJMCbAHEeTjxFLE8yon2giNsT62AbSSNSlTBiQRcHy/pgClTJkQD6x/wA439O7iee9pKs3yGaZpl/GZ82I9xYx9cdPWqlZDNp3nwsN/wCIWviTgHCKjzUD0l7oq2lwSCQSwHh0yJHPElLNE1GaqqMrsrOiyswwYqCDadpjnjQ4ur7HO1K6F9WtWvDkSZtImwH4D5YhbNVSvjmR1j/8hhpxfICrWd6OXqU6diqrLaY/ia56++F3d6h4dU9dR/Q4W0GgehxHwlTyPUj/AGwMSpnlGoSBOk9fwqeZwbmskxYCirlAbF1LMRzn9OmGHEOy2sK9FkOvVNMqVamqkKuotG/TB1Ijiyv086FJYaZPkFt/2g4ynn3YzDGNgLjrzi+CqnZxwdOnSRyDKNrT4mJ5Ylo9n2HOP+8fpieIiaGLlqsWll2iNh87nHb5hybsQOkyD6wBhtS7P6iYIJG4BdjfyAvtjs9nwYI0Gb3nmMB5EiLGwHg9Y94Z0xptE9R1OGXEH/dtjluHCh4hpvC2EHqMS5PKNmHWioEuYu2nkTubDbCPNHgvj0mSUdS4K5mn1QCWIAtBNvK22Duz3EquVLtRTxEd34lJPi3IO4Pnthtk8nS1VFCkhG0zrnVYX8IGGSpSG1Ef9zM36jB8TsVPG+5X+IZqlUpKEyrrWLS9Q1JWwiFU9bGSTecF5HJ0qlGlSUqlZixqNVIVV/Ks3AAF5B5+2HeVpU3dVZadJSwlhT1ECDJhiZvG2OazBGIVwQCYYALImxjlbC662G0FMr5KprKqVcBiNSyQQD8QGkGDvFscLwqu4lFNyY8DEEevri5/tv8A8z/X/wA4jzGaVx4quo/mkT/pgYnisnhorS9n65WSCDF5gAdZ1EWnHA4OZvVQdQayb9bNOLZn81Qei6inNYyVcMRAJZipXY3c3xU6lIj4lI84xHN9mTRXY6/whRvXpyP4nabzcKpnHH+F0ATNdIPIU2PyLKL44q0yF1wdExqi0xIB5A+p64EqZqN1a/PkfQzfBuQKQ4y3BaTLq72rpVWfUKQWybj/ADPEZO0c8S8U4TSoMZFZj4l3UKStjEzaR9MJ14s4XSGYKAbAxYwTte5UH2GJ+Kdp8xWppSrVS9OmZVWYWJuWiJJ3vhtwbHPfZQCBQYqTILVYg+cUxHzxAeJ0lMfsyAj89Sox+jjAPfaiSNJJ3vv6wPrjKpJA2t5/QyROGXvFsPq8UAP+Rlo3H7tv1bGsAK9uQ/v1xmIEsvZinWXN09QbTLb7XVox6GikkAbmw98UPgnaGm9emoRgWYAExF/fHpvZ+kGzFMHafsDjn54tzSZ6P2fmUennL0t/Qruf7HkvLsbgbeEdLEqSduaj3wvzvZBlEoxPkb/UAEf+J9seg9qcue+LMx0ldIUeZKx5mTufLaDKNVWAaerwRKm0woUXIuACDIkeKeYxY8UVtRhXW5pPVf02KRwDIBs3So1UkFiCp5+BiNtxsZG+PR17MZcf+jS2/KOQ9MVbtFU7oJnKQUtTlt5HRlJB/Mw256uuE9H/AKkZtzC0qdr2BP64OOOlNFfVyeZqaXbc9Jp8IpKQBTpj0UD9MF08iB0HpH6HHl+X7eZx20juwx5BDJ+ZwSvaviEwSojf93/XDNpcnOc0i79o82mWoVK1SdCrsLkk2AHuceC/47WEaXMLESZ2sMW7tBxs5lO6zNUmCGVQNB5jVtcXIuCMKM1+wVPhohDa6VnP0cML4sxySW/2Fc0wTKcRbM1QmmHeAqgnSTEbsSQSRO8X5WxbOFcFztBhUWmfFKEfEQDBmIMCYvfFby3D8uXVqRqSpBUgg3BLDalO/wBh0x6Ef+qYG6UJ6BmX7HBlPfYmpdxf3Wa0mmcrUCoWeQgNx4fC0SQbeEE9YxVs92rVGKhCxBg8hINx1xa8527zOZSoqClpKsvgBLJqBUEFmN/a8Y86zHCwol1qrtcrA8xGnmdr288LBwbplrUq2LRwftA1SqDlgwqcoVtY5fgJ6n54X1u01ZahSFsYx12aytXK1UzVPQRoMqYgoIDTLmCSs+Rm1rAZpAudIdSVDmRpLcvLe+Bs3saIR0p+It9hq2fepZiI32/vriOs0I3pgjOZvLlIopDSJITTa9pPthdmq3gNjjPKLs6eDJB49galmnRW0sRubGOWFqcWrE3qH54s3ZU03LIyAm58QBEDSOeH+e4ekJoRAdazCj4RJYbdBi+LUVuc7K9U6SKL+0Nzdj74jzdUgiCfhH649GzGVQJIVdvy/wDGPOczQOlDIgqI/uMCDUt0aJxji2lW51Srt1OCVqnqfniDLZYk/Ev+o/ZTgh8sYgOu1jf9RiSg2yLNhXdEtNarSaZaVBYlRMKN2M2gdcbzmbcKkZh38MkaNOgknwTHi5Gf4vLAdHs9UYhlqyx3gEnmfK3hOD63Z6uW7yrUchjclSSxNyZJ354tUYx2swZMniS1VSIa1J2pqSzmmzeHWSFLgAPABIJGre0g4NrZGnUQAsHroRTCqAiaBAV2csDqJIEuBIIvaMBZnKPT0ioWgg6Lz4Znb8IvMeZxmZ4fUSlUZ1/zdGglrkKdRBv0g38tsFStgeNJXYqzisqAjQNUxDSYEg8z0Pnt1EgrlKhkhGMbkKSPmMPOG0q0hKemTyIU/VgcOs3muIUh3b5gqYkqHFlsBZR62wynRHgT/wCSKJTUnb7xzA3PmcHKhKoZXpNt9+Q6Eb+eG+a4jmGAH7VV53VnE+1hb23xFlaBqEio9SoRsXYiOu5OC5JorUKlXYFThlQqGlIYSJqKJAJXYmRcHfpjMMf8JHJJ/wC/GYTUW6IhPDeHZdK9JlqXDoV8YvDD+uPWeA19GYpE/mj52/XHmOU7PZUVE0s+uzKpbx6l8UMsSIAk+hxfp6Y5+adSi7bo7fs6GvHkjVWWrtKU1BQQumw2EFWlbdDYjqDhRToxJsTBAVRpHUi53JAuTyGB+LdpqZNPvbMARMH+E2KgyJgwQNhvvhZW7R5dJZTqeInxE/IgL9RjR4kXvZz30maPl0sh7eVh+zMp3ZYjzJDfZD9OuPKMmH1eBoMfTFv4tnmrsS5gXjnE7nlJt5bACAAMKOG8JUMO9d0JLBQKerUAJDTqEHyxMeVNsvy9M8WJRfO5Mc/3NLvAFLgrGoDbxaom4MA8sO8znnQiC4U84neLnSSIj+xyq+b4PTLjUaxZizSRTA0L0hmvEX23w1DUnVafdeFFiS+kuOWspedvbDS06U+Tn+FNtkmX4yXzCIrELpks0FybeFZ+HrHmcRAhTDQJMCGOrY9eduXtiXsTkqFWtmRVpJMK9JW28DHWiMbyREEEHCftlSSnXNKgrCmqgiSS0sdTA6uYaRi1RV0jPIsOUcpSLKW2WIIJ6QBzO/vjirXViG8R5+IAmDe5Fh/e2FvZfNH4agJGtWFo/EGuxBtc2F/PF049m6Yqt+7Szydo2mAfxDy6E4WSokUJ+Dqrd6bqCBHKOjLCtIEkiflhZx7WKTl1UBisEM8fFMRpjl1/QYtHEeJqo1UhoDhSsARp3IGkbxYDCzi9bvMkaLQTqF5lv8zVIm07iZkYojWu2aI3Wx3wnLVO6pzTIYIoWSQQI8XmD05wzRthbmcl/wDEy5UMzsFUt4iF0kmIIAubk4sdXtBHdXAlUWIuPDyjcyfrubHCPMcTnNF30vpBIMwSSRA9L7YsUlwM1OTtpkdHLIS2tPhRfhsWMEtsPL2nAiMKZh6Qf8W9tKnxbxyE4e8M4mtapVqVVp6oUqrWjcWBI30jn18sA8Yy7xoQoRuXAP4TqgEMYJAiNjJgxfD6U0IpzVxTYsyeYKOGoLpLmApEwGItMExMfLnsbcKVQ0TV/a27tK5osBoRgQYIGpPExmBe8jFAy9SoapIiWO3JZ5XMAXiBOGNYNTXui8UwwqaWsNYsCQTY232uOlmjpjsyuWqW6BuL8czi1nFGtUNMHwFlUmItMLE46/ZDW7ldUEoSTE/mO1umFuYpt3jHTOoyNIkXHk3lgyszd3SZGKnuxBBiN/64diNeprNZI0Kpp6tRABkCN/KTjtQTiWnltdR2NQCZILSZiTHM7C2JlyxBcSPAYPnBItbEK2HcAOlp5yALxcq4F5HXD3PUswKDKGpyFs/fMSBEEiKZBMTzF4wk4ZpgmGNwQFUE7NybDrjVTQDq1o2iJ7tLArcS1SGN4t/ziqUU5X3LoflKrxXM61pAOCyoVbWbmSCNt7GNuWE+d4gSTrYnTYQZ2YC17iJgYYZw0x3aH4W8Ss1NQwAJAYBWvOnmQCPpqjw9a6rTXvEg1C1bTKtALaYBAViORaPMzh4pLdjS3SiiKlWCKlTvNJaSSwBhTtq0zFiOXMe/ZdfE5dqmpR4oIi4EEafGNKxIiIM47pUadPxLXeVXSoNEo0wOpIjnH1wWvDGqqK3fgFxpANOrYklSDoRty288zviPZh3UaAcpUQ06iioviC/hDGxteDp9iCep2x2EGphlmsy3FQksIu11QLHMeRvi8ZSiaAJapQSB+XQLcizUxJEeW+2Kp2kzJ7kMlRNVhbuwY0BfwX1QB4So+mBFqXAu8eQvJhERQ7NqNzO9yTyEYzFKTOuQNRLEWkvB68288ZiPF7yxZ0lwi51+EeIVjTj4ifCV1naQCB8JHK1ji5g4SZ7tRRqBwF1kqFBZVYK351CQVPkDyw1y7yqnqAfmMczM5UtR3vZUrcl8BN2mHwnzP2H9MIwMPu0Y8Knz/Q4QFWuZAUGJI8gd5jniuKtHSyzUHXqdYuGep5WrURwtKSCxUEllbYmbdeX6zio5ZqYdddWVNjsBtvtO+HA4dSJhFOrSWWarIGUEAsWZgAsxz54fwrW7fyOT1WbxGnCtubY+dcvSpICASdQg8oPInrG/LFTatRWstZDTAIOoEqWDMFiPrzttgimiPWQNlVQlNILgurkMzF0YzuDFiRAGCMtnqpH7qiiKLC5kk28C6Ra0Hp9tNLEkc+GGWa3a+CIsjxKKisNhvppu+/Lwpp3vuMBZDPUquZqnujWJAgMqjTDNqJ17fEB7YMzGZzOgaNDsLM1yAQAWNmGkASbi5B6YHqZUhXqJqFWSaYaA6g3czGnSejDe+BJwknF9/eMuklFWt652OuI5CrUfUlOnTCgG7CAoiSdKm04kXhlWqXdalIBRrcU9VQDkOYk22ucFcG4Q1SmKiZuqzFSrBgAoaxKlRBVRBBJ35cxhrS4HQh07vQxghwYMAWZd9BG5Xcnexxmn1OLEtL3rnn9ypLTJuFoSDILUSDXZlpxJVO7uZ8PimfO3S+A62UQMs62RRGhwU1mSdYZVHKfCT4tJPpas3kSg8F1HIiSOoIHW5mOeknfAhWJQkGTztG2oHqNh76dsGHUqT1LcvUNUVuBZbIo4XTQosSCVJJYRFviE8j0288NsvQVF0LSSmQQAQPiADaioXcypMWsDhTSGh9FOppWqfg52gkrBBWQJ5AgwJ3xLxh6eW0VHbVqMgm5lYhxcnVCkA++GcZyVXz27/wAAySx6kkhrkWahXqVFVGZ6SoYBJ8JYlxax8QFifh9sBdr+KFmQSq01pkkBY1ESyyJFjAEgmAOsjCRe29ZmYUqasSWYW+EEmRymJ6csA8YzWaddLVFhplFB0gC5iBeY2iPTDdO+og1DJVfX6Gaaw8q7Au/NXU+oBmaWIncQZEx9sE1uGEGUqAqYIMC1gY872nHPZukoRu8kAt4SVYg2vJG2ww1zihUZlFJwoJjR0HXVY23xrVCTVPYruX4V3hceEuCFuYjwpceZZoHnbDPK9n6zhV3VFUM6XAkT+KAD5HxeWEebziU6tQXHjBWUDgaLCNQvbf2xZ+CdscvTpikCFCiJ06ZO83PWZ9fLFkvEryqxF4TW73Ic7wCuoASmzEtfUIAHLynr0xLk+E5mmzqKRLQD8QXn0FzIO0ja/TFrpdu8qUANcDr4l8vXCpePyW7usCGsDdp5TyuBynfCp5PQSoXyR8M4VmFY1GKAEzCuHcDbmCCRzgfLFgzuS7ymWJclKjRpCljMaVA06YkiPITPPG8vnFSigqVQSxYuWBE+InaIvbnbE+W4krMVVgylVYAXiCQ48zoM2n4RiqUpPeuC7HFJ0nyVf/8Ayy1W7xkeQgVS86TqTVECAI1afCN/OcEZrha06K5UeGRaRvqNiesMUMWsDiz0cppC+GNI0kmBYHeB15e22BTw5EbvqjlmDAAt8KzbVfcgcyT15YzdTn0xvmvuW44u9kI+EdnmAPeKgWFA1oC1rMAjWX1nYixwZxTO0qKa/CYhCTGofhvbl0wbxKpTdlpCQ1QSvkD4izdDbbfxY8szOcqVqzpRLPq1agIE7Bov4vXe5xkweJ1m83SW9cbf2yyWjEvLuxxR4tVzVQBDB1EAkA6QBOqCCDzjYieWF/aThdevpdG7xUUiGOl5m8K0b7gD5YP4NwGvSVSfAzEliQSUsIURbzb2FwDNndTTALxJsTE7dfWOeNOTqlgklipoOHpHmT17M8cDHrjMeu5zhdCu2upSVjESReBtzxmLF7WxVumK/ZmRPZlIy+cqIoVSIWwIks3nAO/03vtN84S80KUz8C72PwjfHmqZ8+Z8pI/TyOPQOzmZ15em0RYj/wASR+mG6yLUbrubvYuVvI4t3sa7RfAPUfY4h7OZfvNasisganUOoBhHgU+Hn8J9LdRg3jmVc5d6oUlEZQzcgSQAD/5D54reR4h3NQtq0ghZnmCsEQLkECCBy9sVYYXF2buvyK1pp8pr5P6l+/wmigcUlDUqmxie9AMMLg6Ap6AA36TiHNZAqWqlRoMpVSnAVUMkETyNiYHUb3xqnxUrR1oRAuCTJpmLhTsJF9oYEGML6/aimysqUC0mymCIM6w1paSeY98YpRzRm1yc7wKWpVXZjxMp4lqqwUqsakEoFOy0h0IABIHnhTxHhp1DSTp5gMf3IIkqSZGo/X7pcz2qqKwIZaekQoZw2kQR8JkkwTeMCDtUbl9VUCFCgFUBG0ixY+RB54txdNm1e4McixO1JfBbjTJMJ0BVg/hbZKYMlmJ3YkCIHMeeIuLVUQK9TVuzSQQzQxAmJ8CqQbWM+eK6/Gaq2SndQBclze0QIhvLEOfzeaqkMzkkCGgRpJ2UFbmcbl06vdlmXrXzii795Ys1xPuQHpAINagzdqhImW/CEmD4riCBF8FcQ7Z00AAZGYQdRLEB76mAAEnkDIt8sVHN5Md13hENCky0z4tPhJJ1X36RfE3EeywQytalM/CpLXieQiBzOGfT4ZSSkt+z/wBnIlllKTbDj2trspVWZg1gQFpxckwQCd978sAVGrHcKA15jUSNzd5+g54M4Two0ZLgFZ+FiBIsBEXkmx5cvS7dn1pVIZQmhQZCkhtXmATzEzzIEYTNKPT8RSXr/IdEpb3sUDOUa9Jlrly2kzDudz4YIDA8zYXEHlcvc/wupXQMxQKmhiBqc6mW4u5PyE7YveW4QAjie91qAyEbAG6qLSNVp8uWNf4XSJDJKOIIuSCRzt10D2HM4zvr4ypcP6P4Pj9R4Y4p+YqvDez1FQphSdAYgAkiRsYJPQm2xxrNcOp1alNir6DOtghQlWhPDI3B8uWHlV1A8RXWNmp2kmDBWN76uWw33wr4h2po0iNWlzdY3ZpiR4QYa0knrip4surXC2y2ax1Taoj4xku7y5XLh3pQahLkaiCAICqoBUC5kz8XTFCyOfKytUl1PhJI5meUSVjp0Hlh9xTt/WqytFFpj8xux67GB88VdVBGrbVBIFtri+8/LG/pceXQ/GSVvsZMujiDAOLOHrOQYueRxmWyhN1rUgejOU/3gDEjUATM4Jo5FDvjoJ0qMzV7kY4fViy02/kq03P+lpwO+SqAw1J//EnDjK8B7xgqAk7wL2Fzjed4cy1GOxYlto+Izb54OpAoh7NcEqZjMLRT92YLMxBXSikam2vE2HMkDHuHB+GUsrS0IW0ySXqnU5JtcmwtsAPvjzjsn39OsimtAqQSDL6VuRAmASYPyPlj0armUoV6ZYtBsrOC3hceGqFDdQwgRaLXxnyReR1expxeRXW4RUzZIfSGYIAXJEKsmwNiZI8sVXivEdSFIC8oHM7E28rfPBXEOPpTqt8NbXYKwLMxJhG0C+uSd9p5XxTa3EXetp7hkAude48JtAsG9zhX08FVeo7yunYs4px81WNTUVMqhZPCfhjraQBN9sMuyvA6aBc3UDabaCBGhmkeIAm0Mo53J2xWaGWWkjLV8Wl4On8LBeU7kY9R7L9osvUppTp6aekBVX8JHkTcHybfz3wubFWLRDiq2Fwz/EUpep1Spaql5AC2B/FJ5+Qj64n/AGk3QAAKdWq0kmbbWwTn6ShgxUgbAi6iebACV2ibj0wG+WZVJMd3OoruxHO4N5x5nLiljdP4HpYTx5I36glWgWOq977/APOMwwLi2lDBAi0fQ7YzFPiyLFi25PNeH8BQoWdKwiYDwtrQSJt6eWLR2eVVpaUjSGIsZ5AnbnJw14rw7LnLh2XvKtQBiNtN5hVHMdSCd+uEmTytUKWpo/d6iTNyLAEAWNox6LN1Cy464dnH9mVhz6pPamibjfEdFHM0tTxUpKdI+GVrI2o3kGEItO/TAHAMlQzFaK9oRNJDFIjWmokX0ixIB/piDPVg9TTBJ0xabQWk/XEfZ/iZp1VsGGkiD5k6gTyBtfkQDiyCk8aXG38FueUFmntabT+j3LBxHhjUxRo030Coe6Z4Dd5CtU7wBp/dk/j5DVFtw8xwGirL3lSpVSQj63haVYgEAxAakZ3A2O+GvE82yjLusOqVNSk76SrKyE8gJIK8rxbHFbiTSqqqUwQVBjUdBgd2sn4Z6qd98JGOeVJe+/7yY8sYQfmfpQG3Z8AmkKSibBlEKzGFbVeTSBHMSJ54Bz3CwvhDhnTlAcBwPEWjdb2O8DaRhhmaekSiln3IqSpII8LoSCCLc45ROCMnw4hoGZBFiNAgAkw2q4JjcLDA7eunHg075ciX6v8Ako/yowl+FFy+hXcpwxgzGmS2lGcg3kizMJuQAREX25jDajwaqR3gpBIE3HxE2i4kEkEQTufTFmydemjmmKOmGdCR4l16VhV/KrflneADyDDNjwimSpZgJvJJaxBiwgyZ8rRjldT1OSEtNbep08eaOTeG33RXeJdksvVWyhWRdAj/ANSJ1OY+G/TczY4L4bTo0aj5fSx7srU71gSG/L5KAYkz69cd8X4rRpp3feXXWvxamg3BYep53MA3BnCvMdrS5ZaSEK7DW5vCEAMLR0mTivDPPOOiVuL99fP/AFwV5OmU/Pw/Vj7ifZ5K51WD8nEQTclm/MOnnijVqoylTwVkkFZCmWAXrEwSeTRaxwtz+bFWs6LVqMpICIIPhCywLatAXUSSL77HBFKmKerWURRpYwRvDKJZgAIi2hRucdnD0+PFH8SbltxVV87d/oYo5c7bjjpK+Xui08N7VEIz1iiKoAVmMa2uZWLRc7E3j3B4l2tZqbVUUkb6pKg8iVmWNybmJm2POOI1tVV2ViwmxYyY5XN8bzOcqECmX8GlPDsLqDe17nng/wCJiTuEUv79ylZabUt/79i65PNd5lHzNUEl6jKoViEAKhSNOq913PM4rvHONJV7lFXQKUj1kAGBtFvrhzlXReGopqJvq8wS5JG9zfpyxTzlizEj4ZME2tNsNGCc79OCSfloJpUReCu3ofocEZSgSinlA+2NZfIW88M8lk9KiTf5YtvYpFdGhIBg4JShGGC0DtgvIcONR1pqLsY/qcK5VuNQf2Fy7is1XSSqLBYcixAH99MNuLZZu9LxpmAhKAM8tpF4vA6H1tsdw3JomXKLUFiwYXBLXAYibEC3phYmbrvTcLLLTOi+mGJVYhtzAj0+eMa6mMtTvjj3mvRohGlz3/YiyNGqKp8AAFF2BMEq0aaYEHeQAN7W6HG6mUrNUKCpIEFgi+ICJvfxGLeZXlizcP4dSNI1HbTWVAT4iJ+K28EE9MLK/DSqL4tepiTpEiWM+IjcjYTHIYoh1sZtpbB06pqMnQHluMvSyzNSphEDAQ0lgbLrPIzygQJGEOdzrxUYrLtOshZYwTpVdUQL9MWLiXDWrP3NNCquC4SRI+KeQHI2jZvO6+llS1RaYCo0hSRYADeTaIxshlilaJiwTy3xtyyv1eBpWo0ainSjNNQLuxVb6f4iQV/S2A6XCm70sqkAECxMEG3xdP6zi7UKLBNAXUEZ5MyCObCD4vUeW+EtarUDAFWC+EWBBJElhDewjy+ZWXZpMpWJX5ubHmT4lVorJBen+U/5i3EaT+IbmD0w6y+Yo5mmQrB1iCswV8jeQeUiMVvNS1BQG2mJ+gPSJI9CeeAeDIHZxUEFQQXQkEz+E6dxH3xmq6T3Zem0nJbJDPiHF6iuVpy6DZiBf5bjzgYzCsDlTPdKLBYHsb+UYzGLwsHeK/Q06upe6kegcN4Sa1So6MiVBKlImASGYza364PbJDLZeoFQsSSxYwC8wIE7C222LcMjSA8I0x4Rpt6nz63wm44QtNQCSRYTvbn54PVS/wAWOqW/ZUZMeTxZqKKnlsswoBaWkNUMtpWCdQJ8R3MDC1uyWUD91UDNUYlpDaQTckADYASfni6VFbL0jWqMDVe0EbA7i3Pry5YG4llEfLpVo2qEepkfFfp+mMb6zOpUlXqvjwaY6U77evvK7meF05WjRAW+oSS1wpEyxMHTvYzAtiDiXDqSVUBfQxhUi6gxEEGbQOUbTbGuE5bMazVdGAExPh1SIkgwQDJt74X9pkRHFRqniXVoBaAsjdpbxwJG2NuCWdtQnPbvt6+gmaGOnKK3LC/DgSNZlkPdoGJjUxYS0GIZtmG1gdsDUeIZUJUfMrSoV0OksQGWraBbdiIjpMGZJxXuOcY7zL0CtSmnx/vAw+G0IoMtEg3AJtv1rozlGpUSmiio5sGYRyJljd3Nv4cdTF0kIxksju/Tt+2/pRynrlJVt+5b63ahA6DLUiSBZj8MEcxALnS0QQd9+eE/HOMLAVn7sgXvLHyCLJVReATYQMDZ/LEUXLVCCEPhpjQsgGBbxEW/EeWKLVNx/Y2P9+2LcePFTjBUv1f6l7WTp5KTe5Z+H1xWqilTW5BOqpfYTZQY+ZOOe1SoqoBUZmm6sRtBvpUALfywhpaxdSwPl4frvjoZbqPlbDrClK0GXUucWp7v1N0MyyFHWARq3E72298QZp2dgzMWPU/3b2wQ1H4QPPf2x3ToTy/pi1pXZm1Oq7Agok4NbIyZ1p8KjfogFo9MGUcl74Np5PywrYaE+Wyg1bTAF4tzw2pZXrg2nQA2/wCMF0cqTvthGxkgOll+gwWKPU4MFKMaan1wljAmjcDbDvsqVVqhKknRC3iCSCDM225dcC5TImpc2QEAnpM/03OOquV73VTpEBKJDl5uwm6grebEE+eKcuSK2Zt6Xp9b1S4+79BtWziMEP7xlQhavKIE25NuDA69cRVFoq1ZQvdKV1IIu79R0O3zwszJ1FWINOi8rpX4jUkBGIANrETPMY1rLCpXrnTVpN4FJhZsJb12xzp4VymdKcE4elVX6/YIyOZrOPHqeoEBUwAVMx4h1PpyNsPeymYC0KgqumrW7uCQNIZREcvw7+uK42Zb9oY1XVKhpkKFMTsSL2PIj+U+eNcB4GX01mlyWbQ5CtBB/LfVMRccsVZ+mjOFPZFOeEoTr0/vxOsrkjo716rEsxcHUWZVLFlVeYI9YGCOJUKoRmogGoILFuYNg3IA88H1lPdrSlQx0AmNgLcre9hjkZoGpVinNtNMIdiEJMk8tj9LYuU5cp7FUPJ+XYQ53MVqKELUcVGUksOdrlLQN9xBH1NzzGXp57L04a6kM4sfFEcwbXkQdmwoSqSe5psBThi1Rh8BH4JjrO1hGHXD8hSNCnp8Gp2YkSZcEgGTJ5b4xdbNJKXEr2aKnjbd8lV4iaVOVmo1VSQwixINtN5nTvveRywHV7QHT4oZII5hhsLT6bffAHaukEeousRSqHYnWbahebG/n9cAI+hkUuz0g2otA0k73YCw9jGOtCCyY1Ll8/Qry5pyai3sgnNVHRoNMifFcgSDsRJG/wB5xmG9TjlB471SGUaRpgiBsZI88ZilOdb4zT+H/wCv0PZuGdoKVZSdSg2hefnfZvb5YS8QqVKr60XUqMNUmAApBIJ6xy88JOHijWorltQLUPxLBYhmtrEXEna2Emf4vnZqUBVKaGCtY6jIMGmTEpaLkmRgdf0MuomqlVdnx8djJ08vDjrrkufaPi1JoNVgqfxb8jz6+/1GKrmO2gpp3eUTWu2uYk7tNhG/pe3lV+KmmNKuxqOFB/MxaoA07QLFR7eeFNCu6K6jwkssHmPitfa3TpjXh6KMfM936lc8yXlXBYuP8UzDd2TUK6ii+E7alpkk9YLkW6YKzuXpUVCu7VXYSD8RaRAB5ASI25m/SrvVkUzUJJRrEdAweDO/xeW3ti19rXimp5hh/pIxdKCi1EMJNpv0K32wzD1KAGgIFKNG5JYMJ8vS+KllC1Nw6mGXawN4j05+eLPxCpUqUnOnw6KZM2iGtHUX+mK+bYvxx8tFE5PVZutVZzLszH+IzHoNh7AY2tQYj0ziellZ/wCbYeqK3Jvk7Vvljtac7D+mJqeTjffB1DL4NkoWDLnWoN/Cx+q4ZUcn1t7YZ0MvI6DE6UegP9+WFbCgJMqBidaPlGDUpdR+mJkpYUZAVLL3wYtPE4pn2x0FwjHQMafviNkwYyY4KYBBhwOrpR7C3ikmPhHM8hBN8PDlcpVU610nxA8uZsWFvrhFkqY7iuZvoe08tPT3+mKPqehm61TUdb1KoUAw1Qh7QByEb7D54CV3uM3VF2Tg1B6ndq7U+7cCmpJKsSocct77auWIc32dqUXqVagFTUulQARHpvPzwpyHGczTf944LMAfh0x8XhDCGaIFycP8n22prK1tQ6MPFHXbxffEnCndIv6fq8i8jk6+m3xEqURSpA90GrKxKuBr0yTA1EQsTETG+G1YD92qkNLhiA2gmDImDaCJjmJw1y+eymYEhkc72PiHtYj5YRZd2K0O8RQWZVZpOqGDGSSAFIgXBIP0xm8CM91aNHUZpRpunff1+4bRruH1SQWJR+8GpSomAvnff16YEoNVWgFp6SXqOF0kow1FpYx18W1464O4jwFgkU3LKDrgnnOrdpLCbwD1wqrVMwr1u9y4BIXu6g25yYE6bnnyA9qvAl2aYNVq6YZUzd20aqdNTpqMBIGoFgfMzzg4X8T7UtlSuXoqIaQrNINNngTEQQPE0Y6y+cRgol0UqNZABlwANRI2JjfyvGFnHKCV+7rNV8auygCwu1m25CPLfCPp4yklljaElPytwe4j4tWqVKhTwuQdTsN41STjWoyPE1Oj8SFoMsD8Jm8YmSmzMVCqRT+J1MFgZkW5n5YEqEfj1rSEGnyGqZ2N423tjfFJLSuxitklPLJmJqPVCmSIAsIPn1398ax1RpPUUVNdPxXIKGx2jfyxmD8xbPWeGcEoZe9OmqmI1btG8ajJjy2wi4nkKT5zQ7O1OojVGAb4nTQgmNgFwyfPUPws9Y/wif8Ad+mFmbLtmqOlAhKVVGonbwGbc7bY1VbuipNpU3sR8a4ONLCno0QqhT4XAQKq+JSNQhRZjPQjFU4rwZv3YSoNSXbUCrQJ0gLewk3ki+5xc8/RSkuqvXvyG2AGR64CUqJC7ipUlY80Hxe9hiX6h03uiqpw8lCGb4Zadt4B335H2OLTxZUekjIQwsVgyPwk2ne3rg4djEZZqVGap+Y/D6BR/wA4BfgD03grYg+IEREEm5sLdYwssd0wwyJWhFnOIyXQIIZNBLfwsbgD15zhR+yTtgqhmVqVSy3Q69J2m6SR5TIv0wfSyhP9MMoqPAHJvkV0skMFU8v0GGVPJdcN8twZrErHrbAfvIlfAjoZU+uDqOTETF/piw5fg4/EJ8h/d8NP2RdMNTUDlYg/Ob4XUh9Eipplz/7f3bEq0sNq2VUHwyTjT5Vx8SH1Ij64PIHsLwmJBT6jBgpKPXz2xwaZ6f8AOA0SwcLjrT5YnVOeOimFaGTBXGIyuDO5nENWn02wKDYI5s3TQ/8AsbCrJcP0satQ66z/ABN0H5F8vvhtnLI0kfCwv/KeeBjmFgMDYgEe4kemG7C9xVnVq98CphAu02Yk/jBkGOXvgWsAbVKQ9U8B+V1/04aVpYyNsDsJufb1w6EYsqZNPwvB6OI/1LI+gxqjTr0r03cD+A6l99JI+eCalPEHdkGQSD5GD9MMgWNOCdr6tKVdFqKxEkQpH/iIO/li2ZbtDRZqibGkSCGBIuT6gixvaOeKGrlmGoK1xdhffqIP1wfQz60quYqhdRSssg3B/ePtBUi3mfQ7GueCMtzTh6zJiWlboslDiFEVqusKVqEMnwtYKFkbW1KRadsLsxpbMN+6LpHhFMqrDaNIqFZPUDnjz7OP35eogHicnSXBIsAFEhRAiwtaOmIBn8zRtqqKOjXX21SvywFiUVsyueVzlbXc9SfsoCuqkxp6wJDgK56Bj7nCXiHAmpGjTddjKBXN4/m1XkzyGK5kO2OZp7gEfwkr89wflhtR7YJWq0mrFl0NuVBEHf4f6YTRLvTDGUW/QCzfDDrYkbmYKlSPIgHGY9DXjGXqDUtaiwPMOlvI61LA+pOMxV4vuN/+GnxIzs0gGXSABN7Wv1xD2rYrWpFTBCVoItHgG0YzGY3HHXJXOyPjeo7+NhszXI9CbjHoHDB4R541jMKvzFs/yBYwJxxActWkA/u239DjMZh3wZ48nlnZkTTUm5uJNzAJt6YfqMZjMAtHfAkBJkAxtI22xa1UdMZjMJ3C+CQmFOK9WckmST6nGYzDMWJY+D0l7oHSJ6xfBtRQVMjGYzBA+SqZ9AHMADA3TGYzCSHR04ucQtjMZhB0b5D++Zxw2MxmAMRZj4GPPFU4coKyRO32GMxmG7IX1C622NuJW/5cZjMOhBdV3xDjMZggOqA8a/zD7jAuc/y89/8AU/8A7DjWMwUQWLRXun8I58utCmx+t/XAPZyu3eldTafyyY36bY3jMREYw7QUlUqVULO8CPthfVFgcZjMAiIiBjWMxmAQ/9k="
    },
    {
        category: "New Store",
        title: "Small Marjane Store Opens in Agadir’s City Center",
        date: "July 28, 2025",
        image: "https://safartomorocco.com/wp-content/uploads/2025/07/shopping-in-agadir-marjane-market.jpg.webp"
    },
    {
        category: "Partnership",
        title: "Marjane Partners with Local Artisans for Handmade Goods",
        date: "July 25, 2025",
        image: "https://www.gulfafricareview.com/wp-content/uploads/2023/04/Babelmdina-seeks-to-aid-sellers-through-an-online-platform-and-AR-and-AI-tools..jpg"
    },
    {
        category: "Promotion",
        title: "Catalogue Marjane Market Ramadan au 26 Mars 2025",
        date: "July 20, 2025",
        image: "https://promotionaumaroc.com/wp-content/uploads/2023/03/Promo-Marjane-market-au-26-Mars-2023.jpg"
    },
    {
        category: "Innovation",
        title: "Self-Checkout Machines Now Available in All Marjane Stores",
        date: "July 18, 2025",
        image: "https://imageio.forbes.com/specials-images/imageserve/62977578f236a1de7000921f/Mashgin-Smart-Checkout-Circle-K-Lifestyle/1960x0.jpg?format=jpg&width=1440"
    },
    {
    category: "Marjan",
    title: "Marjan Launches Innovative Shopping Experience for Customers",
    date: "December 17, 2024",
    image: "https://www.foodmagazine.ma/wp-content/uploads/2021/11/af3fb4b5-b5f9-48db-a38e-544843dbffdf.jpg"
}

];

const categories = ["Promotion", "New Store", "Event", "Launch", "Community"];
const images = [
    "https://marjane.ma/sites/default/files/styles/banner_full/public/2024-04/fresh-fruits.jpg",
    "https://marjane.ma/sites/default/files/styles/banner_full/public/2023-09/marjane-store-opening.jpg",
    "https://marjane.ma/sites/default/files/styles/banner_full/public/2024-08/back-to-school.jpg",
    "https://marjane.ma/sites/default/files/styles/banner_full/public/2024-05/cooking-event.jpg",
    "https://marjane.ma/sites/default/files/styles/banner_full/public/2024-06/organic-products.jpg"
];

        /**
         * LOOP 1: FOR LOOP - Generate Featured Article
         * Creates the main featured article using loop logic
         */
        function generateFeaturedArticle() {
            const featuredContainer = document.getElementById('featured-article');
            // Use first article from array using FOR loop index
            for (let i = 0; i < 1; i++) {
                const article = newsData[i];
                featuredContainer.innerHTML = `
                    <div class="featured-image" style="background-image: url('${article.image}')"></div>
                    <div class="featured-content">
                        <div class="category">Featured Story</div>
                        <h2>${article.title}</h2>
                        <div class="date">${article.date}</div>
                    </div>
                `;
            }
        }

        /**
         * LOOP 2: FOR LOOP - Generate News Grids
         * Creates multiple news grids with different layouts
         */
        function generateNewsGrids() {
            const newsContainer = document.getElementById('news-container');
            let articleIndex = 1; // Start from second article (first is featured)

            // Create two 2-column grids
            for (let gridIndex = 0; gridIndex < 2; gridIndex++) {
                const grid = document.createElement('div');
                grid.className = 'news-grid two-column';
                
                // FOR LOOP to add 2 articles per grid
                for (let cardIndex = 0; cardIndex < 2; cardIndex++) {
                    if (articleIndex < newsData.length) {
                        const article = newsData[articleIndex];
                        const newsCard = createNewsCard(article);
                        grid.appendChild(newsCard);
                        articleIndex++;
                    }
                }
                
                newsContainer.appendChild(grid);
            }

            // Create one 3-column grid
            const threeColumnGrid = document.createElement('div');
            threeColumnGrid.className = 'news-grid three-column';
            
            // FOR LOOP to add 3 articles to the grid
            for (let cardIndex = 0; cardIndex < 3; cardIndex++) {
                if (articleIndex < newsData.length) {
                    const article = newsData[articleIndex];
                    const newsCard = createNewsCard(article);
                    threeColumnGrid.appendChild(newsCard);
                    articleIndex++;
                }
            }
            
            newsContainer.appendChild(threeColumnGrid);

            // Create additional grids using remaining articles
            const remainingArticles = newsData.length - articleIndex;
            if (remainingArticles > 0) {
                const finalGrid = document.createElement('div');
                finalGrid.className = 'news-grid three-column';
                
                // FOR LOOP for remaining articles
                for (let i = articleIndex; i < newsData.length; i++) {
                    const article = newsData[i];
                    const newsCard = createNewsCard(article);
                    finalGrid.appendChild(newsCard);
                }
                
                newsContainer.appendChild(finalGrid);
            }
        }

        /**
         * Helper function to create individual news cards
         */
        function createNewsCard(article) {
            const newsCard = document.createElement('div');
            newsCard.className = 'news-card';
            
            newsCard.innerHTML = `
                <div class="card-image" style="background-image: url('${article.image}')"></div>
                <div class="card-content">
                    <div class="category">${article.category}</div>
                    <h3>${article.title}</h3>
                    <div class="date">${article.date}</div>
                </div>
            `;
            
            return newsCard;
        }

        /**
         * LOOP 3: FOREACH LOOP - Add Event Listeners
         * Uses forEach to add click events to all news cards
         */
        function addEventListeners() {
            // Wait for cards to be created, then add listeners
            setTimeout(() => {
                const newsCards = document.querySelectorAll('.news-card, .items1');
                
                // FOREACH LOOP to add click events
                newsCards.forEach((card, index) => {
                    card.addEventListener('click', function() {
                        const title = this.querySelector('h2, h3').textContent;
                        alert(`Opening article ${index + 1}: "${title}"`);
                    });
                });
            }, 100);
        }

        /**
         * LOOP 4: FOR...OF LOOP - Handle Scroll Animations
         * Uses for...of loop to animate elements on scroll
         */
        function initScrollAnimations() {
            const observer = new IntersectionObserver((entries) => {
                // FOR...OF LOOP to handle each observed entry
                for (const entry of entries) {
                    if (entry.isIntersecting) {
                        entry.target.classList.add('visible');
                        entry.target.style.transition = 'opacity 0.6s ease, transform 0.6s ease';
                    }
                }
            }, {
                threshold: 0.1
            });

            // Observe all elements that need animation
            setTimeout(() => {
                const animatedElements = document.querySelectorAll('.news-card, .items1, .final-section');
                // FOR...OF LOOP to observe each element
                for (const element of animatedElements) {
                    observer.observe(element);
                }
            }, 200);
        }

        /**
         * LOOP 5: WHILE LOOP - Simulate Loading Process
         * Demonstrates while loop with loading simulation
         */
        function simulateLoading() {
            const loadingElement = document.getElementById('loading');
            let loadingCounter = 0;
            const maxLoading = 3;

            const loadingInterval = setInterval(() => {
                // WHILE LOOP concept: continue while counter is less than max
                loadingCounter++;
                
                if (loadingCounter >= maxLoading) {
                    loadingElement.style.display = 'none';
                    clearInterval(loadingInterval);
                }
            }, 1000);
        }

        /**
         * LOOP 6: FOR...IN LOOP - Process Navigation Items
         * Uses for...in loop to enhance navigation
         */
        function enhanceNavigation() {
            const navItems = {
                'About': '#about',
                'Apply': '#apply', 
                'News': '#news'
            };

            // FOR...IN LOOP to process navigation items
            for (const itemText in navItems) {
                const navLink = document.querySelector(`nav a[href="${navItems[itemText]}"]`);
                if (navLink) {
                    // Add smooth scrolling with loop-generated offset
                    navLink.addEventListener('click', function(e) {
                        e.preventDefault();
                        
                        // Simple animation using loop logic
                        let currentScroll = window.pageYOffset;
                        const targetScroll = 0;
                        const step = (currentScroll - targetScroll) / 10;
                        
                        const scrollAnimation = () => {
                            if (Math.abs(currentScroll - targetScroll) > 1) {
                                currentScroll -= step;
                                window.scrollTo(0, currentScroll);
                                requestAnimationFrame(scrollAnimation);
                            }
                        };
                        
                        scrollAnimation();
                    });
                }
            }
        }

        /**
         * LOOP 7: FOR LOOP - Dynamic Color Generation
         * Generates dynamic colors for categories using loops
         */
        function applyDynamicColors() {
            const colors = ['#32CD32', '#FF6B6B', '#4ECDC4', '#45B7D1', '#FFA726'];
            
            setTimeout(() => {
                const categoryElements = document.querySelectorAll('.category');
                
                // FOR LOOP to apply colors based on index
                for (let i = 0; i < categoryElements.length; i++) {
                    const colorIndex = i % colors.length;
                    categoryElements[i].style.color = colors[colorIndex];
                }
            }, 300);
        }

        /**
         * LOOP 8: FOREACH LOOP - Navbar Scroll Effect
         * Uses forEach to handle scroll effects on navigation
         */
        function initNavbarEffects() {
            window.addEventListener('scroll', function() {
                const nav = document.querySelector('nav');
                const scrollY = window.scrollY;
                
                if (scrollY > 50) {
                    nav.style.backgroundColor = 'rgba(17, 17, 17, 0.95)';
                } else {
                    nav.style.backgroundColor = 'rgba(17, 17, 17, 0.9)';
                }

                // Apply parallax effect to hero title using loop logic
                const heroTitle = document.querySelector('#page1 h1');
                if (heroTitle) {
                    heroTitle.style.transform = `translateY(${scrollY * 0.5}px)`;
                }
            });
        }

        /**
         * MAIN INITIALIZATION FUNCTION
         * Calls all loop-based functions to build the page
         */
        function initializePage() {
            // Execute all loop-based functions
            generateFeaturedArticle(); // FOR loop for featured article  
            generateNewsGrids();       // Multiple FOR loops for news grids
            addEventListeners();       // FOREACH loop for events
            initScrollAnimations();    // FOR...OF loop for animations
            simulateLoading();         // WHILE loop concept for loading
            enhanceNavigation();       // FOR...IN loop for navigation
            applyDynamicColors();      // FOR loop for styling
            initNavbarEffects();       // FOREACH loop for scroll effects

        }

        /**
         * START THE APPLICATION
         * Initialize everything when DOM is ready
         */
        document.addEventListener('DOMContentLoaded', function() {
            console.log('🚀 DOM loaded, initializing loop-based content generation...');
            initializePage();
        });

        /**
         * BONUS: Interactive Loop Demonstration
         * This function demonstrates loops in the console for educational purposes
         */
        function demonstrateLoops() {
            console.log('\n=== JAVASCRIPT LOOPS DEMONSTRATION ===\n');
            
            // 1. FOR LOOP demonstration
            console.log('1. FOR LOOP - Counting articles:');
            for (let i = 1; i <= 5; i++) {
                console.log(`   Article ${i} loaded`);
            }
            
            // 2. WHILE LOOP demonstration
            console.log('\n2. WHILE LOOP - Processing queue:');
            let queueItems = 3;
            while (queueItems > 0) {
                console.log(`   Processing item ${queueItems}`);
                queueItems--;
            }
            
            // 3. FOREACH LOOP demonstration
            console.log('\n3. FOREACH LOOP - Processing categories:');
            categories.forEach((category, index) => {
                console.log(`   ${index + 1}. ${category}`);
            });
            
            // 4. FOR...OF LOOP demonstration
            console.log('\n4. FOR...OF LOOP - Checking images:');
            for (const image of images) {
                console.log(`   ✓ Image URL validated: ${image.substring(0, 50)}...`);
            }
            
            console.log('\n=== LOOPS DEMONSTRATION COMPLETE ===\n');
        }

        // Run loop demonstration
        setTimeout(demonstrateLoops, 1000);


        function loadingpage1(){
  var tl=gsap.timeline()
tl.from("#page1",{
  opacity:0,
  duration:0.3,
  delay:0.2
})
tl.from("#page1",{
  transform:"scaleX(0.7) scaleY(80%)",
  borderRadius:"100px",
  duration:2,
  delay:0.2,
  ease:"expo.out"
})
tl.from("#page1 img",{
    opacity:0,
    duration:0.2,
    delay:0.2
})
 
tl.from("nav",{
  opacity:0,
  delay:-0.2
})
tl.from("#page1 h1 ,#page1 div",{
  opacity:0,
  duration:0.5,
  stagger:0.2
})

}
loadingpage1();


    </script>
</body>
</html>